// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID                pgtype.UUID
	Invoice           string
	Status            string
	Amount            pgtype.Numeric
	Currency          string
	Provider          string
	ProviderPaymentID pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	Email        string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
