// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
  INSERT INTO payments (
      invoice,
      status,
      amount,
      currency,
      provider,
      provider_payment_id
  )
  VALUES (
      $1,
      $2,
      $3,
      $4,
      $5,
      $6
  )
  RETURNING id, invoice, status, amount, currency, provider, provider_payment_id, created_at, updated_at
`

type CreatePaymentParams struct {
	Invoice           string
	Status            string
	Amount            pgtype.Numeric
	Currency          string
	Provider          string
	ProviderPaymentID pgtype.Text
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.Invoice,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.Provider,
		arg.ProviderPaymentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Invoice,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
  SELECT id, invoice, status, amount, currency, provider, provider_payment_id, created_at, updated_at
  FROM payments
  WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Invoice,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
