// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
  INSERT INTO users (
      username,
      password_hash,
      email,
      role
  )
  VALUES (
      $1,
      $2,
      $3,
      $4
  )
  RETURNING id, username, password_hash, email, role, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	Email        string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
  DELETE FROM users
  WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
  SELECT id, username, password_hash, email, role, created_at, updated_at
  FROM users
  WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :one
  SELECT id
  FROM users
`

func (q *Queries) ListUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, listUsers)
	var id int64
	err := row.Scan(&id)
	return id, err
}
